openapi: 3.0.1
info:
  title: monster-mind-flayer-arcanist
  x-cortex-tag: monster-mind-flayer-arcanist
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: aberration
    challenge_rating: 8
    legendary: true
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-mind-flayer-arcanist
      alias: github-token-test
